services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1